# Generated by Django 2.0.5 on 2018-08-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='respondent',
            new_name='complainant',
        ),
    ]
