# Generated by Django 2.0.5 on 2018-08-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_auto_20180820_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='comments',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
